### ISSUE TITLE
RFE: Please rebase on top of the original git repo

### ISSUE THREAD

**Issue by jwrdegoede** [AravisProject/gtk-v4l#3]
Hi,

Great to see that someone has kept gtk-v4l alive during the time that I was working on other things then v4l stuff.

I've sorta come full circle and I'm back on working at v4l things again, so I wanted to use gtk-v4l for some things and found the need to make it work with v4l-subdevs. The (sunset) fedorahosted.org admins have been kind enough to give me a backup of the orginal git repo, with all the history intact.

So after starting with a fork of your repo yesterday, I've now overwritten my fork with the original git history + the patches I worked on yesterday.

This does not include your meson port, I would be happy to add that to my repo, but part of the git-history which is not in the 0.4 tarbal you used as a starting point is a re-licensing from GPLv2+ to LGPLv2+, because Huzaifa and I hoped that oneday the code in the lib dir could be build into a .so and actually used by other programs to show v4l controls by re-using the main widget for this.

Since you meson port is based on the GPLv2+ version, just cherry-picking it on top of the LGPGv2+-ed git tree I have now felt wrong (at least doing so without your permission).

Note ATM I have no big plans with gtk-v4l, I just needed something to easily poke at controls on v4l-subdevs.

Still I thought it would be good for you to know that the original git history is now available and let you know that you may want to rebase (which will unfortunately require a forced push).

My git repo with the original history is here:
https://github.com/jwrdegoede/gtk-v4l/

**Comment by EmmanuelP** [comment]
Hi Hans,

Le ven., nov. 12 2021 at 01:09:26 -0800, Hans de Goede 
***@***.***> a écrit :
> This does not include your meson port, I would be happy to add that 
> to my repo, but part of the git-history which is not in the 0.4 
> tarbal you used as a starting point is a re-licensing from GPLv2+ to 
> LGPLv2+, because Huzaifa and I hoped that oneday the code in the lib 
> dir could be build into a .so and actually used by other programs to 
> show v4l controls by re-using the main widget for this.
> 
> Since you meson port is based on the GPLv2+ version, just 
> cherry-picking it on top of the LGPGv2+-ed git tree I have no felt 
> wrong (at least doing so without your permission).
> 

I have no issue with LGPL v2+, this is my license of choice for my own 
projects. Feel free to cherry-pick what you want in my repository.

I don't have any futur plan about gtk-v4l. I think it would be better 
to just keep one repository. I can delete mine when you are done 
cherry-picking useful stuff from it.

Cheers,

	Emmanuel.

**Comment by EmmanuelP** [comment]
>  I can delete mine when you are done
cherry-picking useful stuff from it.

Alternatively, we can keep the repository in Aravis project. At some point, there should be a v4l2 interface in Aravis, so it make sense to have gtk-v4l here. I can add you as an admin of the repository inside Aravis-project.

**Comment by jwrdegoede** [comment]
Thank you. I've cherry-picked the still relevant commits from your version on top of:
https://github.com/jwrdegoede/gtk-v4l/

I agree that it would be good to have only 1 repo (to avoid confusion). I don't really have a preference, so you can either do a forced push to the Aravis repo with the latest contents of my repo and add me as an admin (and then I will delete my repo), or you can delete the Aravis repo.

**Comment by EmmanuelP** [comment]
I'm going to delete my repository, it is the easier and faster thing to do. Thanks.
